### ISSUE TITLE
Multiple sources doesn't work (as expected)

### ISSUE THREAD

**Issue by rtempleton** [chunqishi/json2json#1]
I have a case where I need to include more than 1 source document (source and dummy below). The transform function shows accepting multiple sources but nothing after the first source is found during parsing...

testcase1.source.json
{"a":1,"d":2}

testcase1.dummy.json
{"c":1}

testcase1.template.json
{
	"b":"&$.a",
	"c":"&$.c"
}

Think of the "dummy" doc as containing boilerplate keys but with dynamic values that can get picked up at runtime rather than hardcoding them in the template...

@Test
    public void testCase1() throws Exception{
    	JsonObject source = readJsonObject("testcase1.source.json");
    	JsonObject dummy = readJsonObject("testcase1.dummy.json");
    	JsonObject template = readJsonObject("testcase1.template.json");
    	JsonObject expected = readJsonObject("testcase1.expected.json");
    	String result = Json2Json.transform(template.toString(), source.toString(), dummy.toString());
    	System.out.println("Result : " + result.toString());
    }

testcase1.expected.json
{"b":1,"c":1}

Get the following exception:
Result : {"b":"1","c":{"Exception":"com.jayway.jsonpath.PathNotFoundException: No results for path: $['c']\n\tat com.jayway.jsonpath.internal.token.PathToken.handleObjectProperty(PathToken.java:53)\n\tat com.jayway.jsonpath.internal.token.PropertyPathToken.evaluate(PropertyPathToken.java:44)\n\tat com.jayway.jsonpath.internal.token.RootPathToken.evaluate(RootPathToken.java:53)\n\tat com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:53)\n\tat com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:61)\n\tat com.jayway.jsonpath.JsonPath.read(JsonPath.java:178)\n\tat com.jayway.jsonpath.internal.JsonReader.read(JsonReader.java:146)\n\tat com.jayway.jsonpath.internal.JsonReader.read(JsonReader.java:135)\n\tat com.jayway.jsonpath.JsonPath.read(JsonPath.java:461)\n\tat org.lappsgrid.json2json.jsonpath.JayWayJsonPath.path(JayWayJsonPath.java:37)\n\tat org.lappsgrid.json2json.jsonpath.JsonPath.path(JsonPath.java:56)\n\tat org.lappsgrid.json2json.template.JsonPathRefUnit.transform(JsonPathRefUnit.java:70)\n\tat org.lappsgrid.json2json.template.JsonUnit.transform(JsonUnit.java:70)\n\tat org.lappsgrid.json2json.template.JsonUnit.transform(JsonUnit.java:82)\n\tat org.lappsgrid.json2json.template.JsonTemplate.transform(JsonTemplate.java:31)\n\tat org.lappsgrid.json2json.Json2Json.transform(Json2Json.java:34)\n\tat com.hwx.slb.studio2.xform.XformTestCase.testCase1(XformTestCase.java:49)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:606)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:236)\n\tat org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)\n\tat org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)\n"}}

**Comment by chunqishi** [comment]
Hi, rtempleton,

I am sorry that, I do not make it clear. 
For multiple input cases.  You need identify whose jsonpath.
I assume you provide an index (0, 1, 2) after & mark.

Thus, the template should be 
-----------------------------------------------------
{
  "b":"&$.a",
  "c":"&1$.c"
}
-----------------------------------------------------

**Comment by rtempleton** [comment]
Great! Thank you!
